### PR TITLE
fix: Use the specced olm session config v1 by default

### LINKED ISSUE #40: Outbound Olm messages are not spec-compliant
This line uses the default SessionConfig: https://github.com/famedly/dart-vodozemac/blob/main/dart/lib/src/api.dart#L384 which due to an upstream vodozemac bug (https://github.com/matrix-org/vodozemac/issues/280) is set to `version_2`, even though only `version_1` is in the spec.

It might be a reasonable solution to wait for upstream to fix the default, but you could also hardcode `version_1` here to fix it right away. That's what matrix-rust-sdk does: https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/identities/device.rs#L736

### PR DESCRIPTION
**Pull request by krille-chan**
closes #40

### CODE REVIEW

File: dart/test/vodozemac_test.dart [hunk 1]
```diff
@@ -112,6 +114,14 @@ void main() async {
       final outboundSession = account2.createOutboundSession(
           identityKey: account.curve25519Key, oneTimeKey: onetimeKey);
       check(outboundSession.hasReceivedMessage).isFalse();
+      expect(outboundSession.sessionConfig.version(), 1);
```
Comment (td-famedly) [inline dart/test/vodozemac_test.dart]: can you also add a test and make sure it's backwards compatible? i.e will v2 messages be decryptable by this change?

Comment (krille-chan) [reply dart/test/vodozemac_test.dart]: I changed the test so that it tests both versions

Comment (td-famedly) [reply dart/test/vodozemac_test.dart]: nice

**Review by td-famedly — APPROVED** [review]
lg!

**Comment by td-famedly** [comment]
@krille-chan can you merge main and then merge this? ty!
